### ISSUE TITLE
h3-worldmap.js: remove that from arglistsIn 

### ISSUE THREAD

**Issue by rudifa** [olange/h3-worldmap#11]
in Template fragments closures `mapViewFrag` and `mapViewOrSpinner`, replace argument `that` by specific values needed in these fragments.

**Comment by rudifa** [comment]
Proposed in PR#13

**Comment by olange** [comment]
Changes equivalent to effects of PR #13 have been contributed to PR #1 in commit d512feb on 27.04.2022 by @rudifa and @olange (gongfuio/sessions#521). It can be closed without merging the conflicts, as the solutions differ a little bit.
